valor = float(input('Digite um valor em metros: '))
print('Em kilómetros serão: {:.0f}km'.format(valor/1000))
print('Em centímetros serão: {:.0f}hm'.format(valor/100))
print('Em centímetros serão: {:.0f}dam'.format(valor/10))
print('Em centímetros serão: {:.0f}dm'.format(valor*10))
print('Em centímetros serão: {:.0f}cm'.format(valor*100))
print('Em milímetros serão: {:.0f}mm'.format(valor*1000))